const books = [
    {
        title: "Peter Norton's Assembly Language Book for the IBM PC",
        cover: "https://i.imgur.com/IdLdRgq.jpg",
        authors: ["Peter Norton", "John Socha"],
        description: "Programmers wanting to develop full-fledged programs in assembly language need this book. The more than 100,000 programmers who made the first edition an instant classic Norton and Socha team up to produce a primer for serious users.",
        available: true,
    },
    {
        title: "The Design and Analysis of Computer Algorithms",
        cover: "https://i.imgur.com/Fcclg6e.jpg",
        authors: ["Alfred V. Aho", "John E. Hopcroft", "Jeffrey D. Ullman"],
        description: "In 1974, Aho, John Hopcroft, and Ullman wrote the Design and Analysis of Computer Algorithms, codifying some of their early research on algorithms. This book became one of the most highly cited books in computer science for several decades and helped to stimulate the creation of algorithms and data structures as a central course in the computer science curriculum.",
        available: true,
    },
    {
        title: "Artificial Intelligence A Modern Approach",
        cover: "https://i.imgur.com/nT9d80D.jpg",
        authors: ["Stuart J. Russell", "Peter Norvig"],
        description: "Artificial Intelligence: A Modern Approach is a university textbook on artificial intelligence, written by Stuart J. Russell and Peter Norvig. It was first published in 1995 and the fourth edition of the book was released on 28 April 2020.",
        available: true,
    },
    {
        title: "SoftICE Command Reference",
        cover: "https://i.imgur.com/VBho66j.jpg",
        authors: ["Compuware Corporation"],
        description: "This SoftIce reference contains most SoftIce commands.",
        available: true,
    },
    {
        title: "An Introduction to the Theory of Computation",
        cover: "https://i.imgur.com/n3ciAe9.jpg",
        authors: ["Dr. Walid G. Aref", "1995, 1996 and 1997 students"],
        description: "This course introduces the student to fundamental issues in the theory of computation, The students will learn the capabilities and limitations of alternative models of computation, complexity classes, and undecidable problems",
        available: true,
    },
    {
        title: "Quantum Computation and Quantum Information",
        cover: "https://i.imgur.com/BQ9GEXN.jpg",
        authors: ["Michael A. Nielsen", "Isaac L. Chuang"],
        description: "One of the most cited books in physics of all time, Quantum Computation and Quantum Information remains the best textbook in this exciting field of science. This comprehensive textbook describes such remarkable effects as fast quantum algorithms, quantum teleportation, quantum cryptography and quantum error-correction. Quantum mechanics and computer science are introduced before moving on to describe what a quantum computer is, how it can be used to solve problems faster than 'classical' computers and its real-world implementation. It concludes with an in-depth treatment of quantum information. Containing a wealth of figures and exercises, this well-known textbook is ideal for courses on the subject, and will interest beginning graduate students and researchers in physics, computer science, mathematics, and electrical engineering.",
        available: true,
    },
    {
        title: "Nonlinear Programming: Theory and Algorithms",
        cover: "https://i.imgur.com/ukDclAn.jpg",
        authors: ["Mokhtar S. Bazaraa", "Hanif D. Sherali", "C. M. Shetty"],
        description: "Nonlinear Programming: Theory and Algorithms addresses the problem of optimizing an objective function in the presence of equality and inequality constraints. Many realistic problems cannot be adequately represented as a linear program owing to the nature of the nonlinearity of the objective function and/or the nonlinearity of any constraints.",
        available: true,
    },
    {
        title: "How Microprocessors Work",
        cover: "https://i.imgur.com/tGVFHhn.jpg",
        authors: ["Tucker Hammerstrom", "Gregg Wyant"],
        description: "Unravels the mysteries of microchips for the common reader, employing illustrations and concise text to detail how they work, why some are better than others, memory and performance, memory caching, and more.",
        available: true,
    },
    {
        title: "Advanced Data Communications and Networks",
        cover: "https://i.imgur.com/I1HTCAn.jpg",
        authors: ["W. Buchanan"],
        description: "The use of data communications and computer networks is constantly increasing, bringing benefits to most of the countries and peoples of the world, and serving as the lifeline of industry. Now there is a textbook that discusses data communications and networking in a readable form that can be easily understood by students who will become the IS professionals of the future.",
        available: true,
    },
    {
        title: "Feedback Control System Analysis and Synthesis",
        cover: "https://i.imgur.com/imYNqkt.jpg",
        authors: ["J. J. D'Azzo"],
        description: "The main objective in writing this book has been to produce a good textbook from the student's point of view on feedback controls that would unify the diverse methods of analysis and would present the fundamentals explicitly and clearly. This enlarged second edition gives the material in a sequence that, in the authors' experience, enables the reader to understand and apply the basic principles. Terminology and definitions are introduced and explained as needed; emphasis is placed on the topics considered most important; and the material is arranged for ease in understanding.",
        available: true,
    },
    {
        title: "Invitation to Computer Science: Java version",
        cover: "https://i.imgur.com/Cb1SON4.jpg",
        authors: ["Schneider, G. Michael"],
        description: "This edition of Invitation to Computer Science follows the breadth-first guidelines recommended by CC2001 to teach computer science topics from the ground up. The authors begin by showing that computer science is the study of algorithms, the central theme of the book, then move up the next five levels of the hierarchy: hardware, virtual machine, software, applications, and ethics. Utilizing rich pedagogy and a consistently engaging writing style, Schneider and Gersting provide students with a solid grounding in theoretical concepts, as well as important applications of computing and information technology. A laboratory manual and accompanying software is available as an optional bundle with this text",
        available: true,
    },
    {
        title: "Principles of Computer Hardware",
        cover: "https://i.imgur.com/K6b1pae.png",
        authors: ["Alan Clements"],
        description: "The book opens with an introduction to the fundamental concepts behind computer architecture: gates, circuits, logic, and computer arithmetic. It goes on to discuss computer operation from instruction set architecture and assembly language programming to the central processing unit. Then, the text builds on these foundations; explaining how the hardware interfaces with its surroundings, introducing computer memory, operating systems, and computer peripherals.",
        available: true,
    },
    {
        title: "Modern Control Systems 11th edition",
        cover: "https://i.imgur.com/txapmQ2.png",
        authors: ["Richard C. Dorf", "Robert H. Bishop"],
        description: "Written to be equally useful for all engineering disciplines, this book is organized around the concept of control systems theory as it has been developed in the frequency and time domains. It provides coverage of classical control employing root locus design, frequency and response design using Bode and Nyquist plots. It also covers modern control methods based on state variable models including pole placement design techniques with full-state feedback controllers and full-state observers. The book covers several important topics including robust control systems and system sensitivity, state variable models, controllability and observability, computer control systems, internal model control, robust PID controllers, and computer-aided design and analysis. For all types of engineers who are interested in a solid introduction to control systems.",
        available: true,
    },
    {
        title: "Problem Solving with C++ 7th edition",
        cover: "https://i.imgur.com/KldvOYL.png",
        authors: ["Walter Savitch"],
        description: "Problem Solving with C++ is written for the beginning programmer. The text cultivates strong problem-solving skills and programming techniques as it introduces readers to the C++ programming language. Author Walt Savitch’s approach to programming emphasizes active reading through the use of well-placed examples and self-tests, while flexible coverage means the order of chapters and sections can easily be adapted without sacrificing continuity. Savitch’s clear, concise style is a hallmark feature of the text and is supported by a suite of tried-and-true pedagogical tools.",
        available: true,
    },
    {
        title: "Algorithms: Sequential, Parallel, and Distributed",
        cover: "https://i.imgur.com/dRDlXXj.png",
        authors: ["Kenneth A. Berman", "Jerome L. Paul"],
        description: "Algorithms: Sequential, Parallel, and Distributed offers in-depth coverage of traditional and current topics in sequential algorithms, as well as a solid introduction to the theory of parallel and distributed algorithms. In light of the emergence of modern computing environments such as parallel computers, the Internet, and cluster and grid computing, it is important that computer science students be exposed to algorithms that exploit these technologies. Berman and Paul's text will teach students how to create new algorithms or modify existing algorithms, thereby enhancing students' ability to think independently.",
        available: true,
    },
    {
        title: "Head First Design Patterns",
        cover: "https://i.imgur.com/qpPbmWp.png",
        authors: ["Eric Freeman", "Elisabeth Robson"],
        description: "NOTE: The only available version of the book is a printed one, featuring only the following chapters: 1, 3, 5, 7, 11, and the appendix.",
        available: true,
    },
{
    title: "Beginner's Guide to Microprocessors",
    cover: "https://i.imgur.com/u60aBZC.jpg",
    authors: ["Charles M. Gilmore"],
    description: "Gives Details on BASIC Logic, & Demonstrates the Microprocessor's Function as Integrated Circuit. Also Covers I/O Devices & Systems Software",
    available: true,
},
{
    title: "Systems Engineering and Analysis",
    cover: "https://i.imgur.com/bLJOID1.jpg",
    authors: ["W. J. Fabrycky", "J. H. Mize"],
    description: "This practical introduction to Systems Engineering provides systems engineers and analysts with the concepts, methodologies, models and tools needed to understand and implement the systems approach. It views systems from a top-down, integrated, life-cycle perspective, evolving in coverage from the identification of a consumer need to design and development, production/construction, distribution, system utilization and support, retirement, and material recycling and/or disposal. Note : the only available version of the book is printed one, featuring only Part 1 (simulation fundamentals ) and index from part 2(simnet simulation language).",
    available: true,
},
{
    title: "Engineering Statistics",
    cover: "https://i.imgur.com/9iIgmxh.jpg",
    authors: ["Professor Khalid M. Ahmed", "Professor Soheir A. Fouad"],
    description: "the material in this book has been used in teaching a (3unit) one semester course to the undergraduate students of C.S .",
    available: true,
},
{
    title: "CSED THIRD YEAR EXAMS SECOND TERM",
    cover: "https://imgur.com/DPDZSgi.jpg",
    authors: [],
    description: "Exams of 'Algorithms and DSP / System programming / Numerical Analysis / Switching / Electronics' UNTIL 1998",
    available: true,
},
{
    title: "CSED THIRD YEAR EXAMS FIRST TERM",
    cover: "https://imgur.com/10aT1uX.jpg",
    authors: [],
    description: "Exams of 'Automatic control / Discrete mathematics / Electronics / File structure' UNTIL 1998",
    available: true,
},
    {
        title: "Intermediate Mathematics (Analysis)",
        cover: "https://i.imgur.com/MdEGBT0.png",
        authors: ["Usherwood", "Trimble"],
        description: "This book is an intermediate-level textbook on mathematical analysis. It covers topics such as limits, continuity, differentiation, integration, and series. It is intended for students who have already had a calculus course.",
        available: true,
    },
    {
        title: "Checking Experiments in Sequential Machines",
        cover: "https://i.imgur.com/IzzC0tC.png",
        authors: ["ASOK BHATTACHARYYA"],
        description: "I couldn't find much information about this book online. However, the title suggests that it is about a method for checking the correctness of experiments in sequential machines. Sequential machines are a type of finite state machine in which the output depends only on the current state and the input.",
        available: true,
    },
    {
        title: "Systems Software: An Introduction to Systems Programming",
        cover: "https://i.imgur.com/2odTwLe.png",
        authors: ["Leland L. Beck"],
        description: "This book is an introduction to systems programming. It covers topics such as operating systems, memory management, compilers, and interpreters. It is intended for students who have a good understanding of computer architecture and programming.",
        available: true,
    },
    {
        title: "Statistical Consulting",
        cover: "https://i.imgur.com/u8rwBE7.png",
        authors: ["Javier Cabrera", "Andrew McDougall"],
        description: "This book is a guide to statistical consulting. It covers topics such as how to find clients, how to scope projects, how to analyze data, and how to communicate results. It is intended for statisticians who want to start their own consulting business.",
        available: true,
    },
    {
        title: "Fundamentals of Logic Design 4th edition",
        cover: "https://i.imgur.com/EZb7i5Q.png",
        authors: ["Charles H. Roth, Jr"],
        description: "This book is an introduction to logic design. It covers topics such as Boolean algebra, combinational logic, sequential logic, and programmable logic devices. It is intended for students who are interested in designing digital circuits.",
        available: true,
    },
    {
        title: "Introduction to Algorithms (CLRS) 2nd edition",
        cover: "https://i.imgur.com/2Dg6YRG.png",
        authors: ["CLRS"],
        description: "This book is a classic textbook on algorithms. It covers topics such as data structures, sorting, searching, graph algorithms, and dynamic programming. It is intended for students who want to learn about the design and analysis of algorithms.",
        available: true,
    },
    {
        title: "Compilers: Principles, Techniques & Tools 2nd edition (Dragon Book)",
        cover: "https://i.imgur.com/2cgexB4.png",
        authors: ["Alfred V.Aho", "Monica S. Lam", "Ravi Sethi", "Jeffery D. Ullman"],
        description: "This book is a comprehensive textbook on compiler design. It covers topics such as lexical analysis, syntax analysis, semantic analysis, code generation, and code optimization. It is intended for students who want to learn how compilers work.",
        available: true,
    },
     {
        title: "Computer Organization And Design: The Hardware/Software Interface 3rd edition",
        cover: "https://i.imgur.com/pVhwlpa.png",
        authors: ["David A. Patterson", "John L. Hennessy"],
        description: "This book is a classic textbook on computer organization and design. It covers topics such as computer architecture, pipelining, memory hierarchies, and I/O systems. It is intended for students who want to learn about how computers work.",
        available: true,
    },
     {
        title: "Fundamentals Of Database Systems 3rd edition",
        cover: "https://i.imgur.com/K2KxWv1.png",
        authors: ["ElMasri", "Navathe"],
        description: "This book is an introduction to database systems. It covers topics such as the relational model, SQL, database design, and database administration. It is intended for students who want to learn about how databases work.",
        available: true,
    },
    {
        title: "Mulitmedia: Making It Work 8th edition",
        cover: "https://i.imgur.com/WCAMBOg.png",
        authors: ["Tay Vaughan"],
        description: "This book is an introduction to multimedia. It covers topics such as digital audio, digital video, digital images, and multimedia authoring. It is intended for students who want to learn about how to create and use multimedia applications.",
        available: true,
    },
    {
        title: "Variations In C: Programming techniques for developing efficient professional applications",
        cover: "https://i.imgur.com/Y3SGJ2Q.png",
        authors: ["Steve Schustack"],
        description: "This book is a collection of programming techniques for developing efficient C applications. It covers topics such as memory management, pointers, and data structures. It is intended for experienced C programmers who want to improve their coding skills.",
        available: true,
    },
     {
        title: "Infinite Sequences And Series",
        cover: "https://i.imgur.com/ttpKIdR.png",
        authors: ["Professor Konrad Knopp Translated by F. Bagemihl"],
        description: "This book is an introduction to the theory of infinite sequences and series. It covers topics such as convergence, divergence, tests for convergence, and series operations.",
        available: true,
    },
    {
        title: "Theory of Sets",
        cover: "https://i.imgur.com/Mv5zPW2.png",
        authors: ["E. Kamke translated from the second German edition by F. Bagemihl"],
        description: "This book is an introduction to the theory of sets. It covers topics such as set operations, functions, relations, and cardinal numbers.",
        available: true,
    },
    {
        title: "Summation Of Series",
        cover: "https://i.imgur.com/eM93JGT.png",
        authors: ["L.B. W. Jolley"],
        description: "This book is a collection of problems and solutions related to the summation of series.",
        available: true,
    },
    {
        title: "C: The Programming Language",
        cover: "https://i.imgur.com/rdBUnIi.png",
        authors: ["Brian W. Kernighan", "Dennis M. Ritchie"],
        description: "This book is a classic introduction to the C programming language. It covers topics such as syntax, semantics, and the C standard library.",
        available: true,
    },
    {
        title: "The Art of Computer Programming Volume 3: Sorting and Searching 2nd edition",
        cover: "https://i.imgur.com/5uvm8sy.png",
        authors: ["Donald E. Knuth"],
        description: "This book is a comprehensive introduction to the algorithms for sorting and searching. It covers topics such as insertion sort, merge sort, quicksort, heaps, binary search trees, and hash tables.",
        available: true,
    },
    {
        title: "Operating Systems: Internals and Design Principles 5th edition",
        cover: "https://i.imgur.com/PJQelkT.png",
        authors: ["William Stallings"],
        description: "This book is an introduction to the design and implementation of operating systems. It covers topics such as processes, threads, memory management, scheduling, and I/O.",
        available: true,
    },
    {
        title: "Computer Networks 4th edition",
        cover: "https://i.imgur.com/y9o2WdH.png",
        authors: ["Andrew S. Tanenbaum"],
        description: "This book is an introduction to the principles of computer networks. It covers topics such as the OSI model, TCP/IP, routing, and network security.",
        available: true,
    },
    {
        title: "Digital Signal Processing",
        cover: "https://imgur.com/pFbXZA9.jpg",
        authors: ["William D. Stanley"],
        description: "this book provide an introductory treatment of the concepts of DSP with suitable supporting work in linear system concepts and filter design ",
        available: true,
    },
    {
        title: "Fundamentals of Logic Design Sixth Edition",
        cover: "https://i.imgur.com/Q220HRx.jpg",
        authors: ["Charles H. Roth, Jr."],
        description: "this book achieves yet again an unmatched balance between theory and application. Authors Charles H. Roth, Jr. and Larry L. Kinney carefully present the theory that is necessary for understanding the fundamental concepts of logic design while not overwhelming students with the mathematics of switching theory. Divided into 20 easy-to-grasp study units, the book covers such fundamental concepts as Boolean algebra, logic gates design, flip-flops, and state machines. By combining flip-flops with networks of logic gates, students will learn to design counters, adders, sequence detectors, and simple digital systems. After covering the basics, this text presents modern design techniques using programmable logic devices and the VHDL hardware description language.",
        available: true,
    },
    {
        title: "Fundamentals Of Electric Circuits Third Edition",
        cover: "https://i.imgur.com/Sx2dpUX.jpg",
        authors: ["Alexander, Charles K"],
        description: "This book is a coverage of elementary circuit theory is encyclopedic. For someone who needs a quick refresher here and there, this is great.",
        available: true,
    },
    {
        title: "Digital Fundamentals 10th Edition",
        cover: "https://i.imgur.com/8rCOHB8.jpg",
        authors: ["Tomas L. Floyd"],
        description: "This book provides thorough, up-to-date coverage of digital fundamentals, from basic concepts to microprocessors, programmable logic, and digital signal processing",
        available: true,
    },
];

